# Generated by Django 3.2 on 2021-05-13 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('model', models.CharField(max_length=30)),
                ('company', models.CharField(max_length=30)),
                ('category', models.CharField(choices=[('Bike', 'Bike'), ('Camera', 'Camera'), ('Car', 'Car')], max_length=10)),
            ],
        ),
    ]
