# Generated by Django 3.2 on 2021-05-13 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='price',
            field=models.IntegerField(default=1200, help_text='Please Just Specify The Price In Rupees Per Hour Only', max_length=5),
        ),
    ]
