# Generated by Django 3.2 on 2021-05-13 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_rename_products_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(help_text='Please Just Specify The Price In Rupees Per Hour Only'),
        ),
    ]
