# Generated by Django 3.2 on 2021-05-16 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20210516_0157'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='staus',
            field=models.CharField(choices=[('A', 'Available'), ('R', 'Rented'), ('NA', 'Not Available')], default='available', help_text=["A - 'Availabe'", "R - 'Rented'", "NA - 'Not Availabe'", 'Default is A'], max_length=20),
        ),
    ]
