# Generated by Django 3.2 on 2021-05-16 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_product_staus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='staus',
            field=models.CharField(choices=[('Available', 'A'), ('Rented', 'R'), ('Not Available', 'NA')], default='available', help_text="A - 'Availabe'(Default)<br/>R - 'Rented'<br>NA - 'Not Availabe' ", max_length=20),
        ),
    ]
