# Generated by Django 3.2 on 2021-05-16 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_product_staus'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='category',
            field=models.CharField(choices=[('Bike', 'Bike'), ('Camera', 'Camera'), ('Car', 'Car')], default='bike', max_length=10),
            preserve_default=False,
        ),
    ]
