# Generated by Django 3.2 on 2021-05-14 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='support',
            new_name='issues',
        ),
    ]
