# Generated by Django 3.2 on 2021-05-14 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_support_issues'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='issues',
            new_name='issue',
        ),
    ]
