# Generated by Django 3.2 on 2021-05-16 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='user',
            new_name='username',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='propic',
            field=models.ImageField(default='uploads/images/userprofilepics/default.png', upload_to='uploads/images/userprofilepics/'),
        ),
    ]
